version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      USER_SERVICE_URL: http://user-service:8081
      NOTIFICATION_SERVICE_URL: http://notification-service:8082
      AUTH_SERVICE_ADDR: http://user-service:8081
      KAFKA_BROKERS: kafka:9092

  user-service:
    build: ./user
    ports:
      - "8081:8081"

  notification-service:
    build: ./notification
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      TWILIO_ACCOUNT_SID: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      TWILIO_AUTH_TOKEN: your_auth_token
      KAFKA_BROKERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:29092"]
      start_period: 40s
      interval: 5s
      timeout: 10s
      retries: 5