apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: wuphf-dot-com-notification-service:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_BROKERS
          value: "kkafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: NodePort
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: notification