apiVersion: v1
kind: Service
metadata:
  name: kkafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kkafka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kkafka
spec:
  serviceName: kkafka
  replicas: 1
  selector:
    matchLabels:
      app: kkafka
  template:
    metadata:
      labels:
        app: kkafka
    spec:
      containers:
      - name: kkafka
        image: confluentinc/cp-kafka:latest
        env:
        - name: "KAFKA_BROKER_ID"
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kkafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        ports:
        - containerPort: 9092