name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build and test User service
      uses: goreleaser/goreleaser-action@v4
      with:
        workdir: ./user/cmd
        args: build --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and test Notification service
      uses: goreleaser/goreleaser-action@v4
      with:
        workdir: ./notification/cmd
        args: build --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and test API Gateway
      uses: goreleaser/goreleaser-action@v4
      with:
        workdir: ./api-gateway/cmd
        args: build --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
  
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        push: false

