name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build and Test
      uses: goreleaser/goreleaser-action@v4
      with:
        release: main
        args: release --clean

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
  
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        push: false

